name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6

      - name: Build exe (PyInstaller onefile)
        shell: pwsh
        run: |
          pyinstaller `
            --windowed `
            --name SmartTimers `
            --clean `
            --noconfirm `
            --onefile `
            --collect-all PySide6 `
            --hidden-import PySide6.QtMultimedia `
            SmartTimers.py

      - name: Install Inno Setup
        shell: pwsh
        run: |
          choco install innosetup -y --no-progress

      - name: Build installer (Inno Setup)
        shell: pwsh
        run: |
          $paths = @(
            "$env:ProgramFiles(x86)\Inno Setup 6\ISCC.exe",
            "$env:ProgramFiles\Inno Setup 6\ISCC.exe"
          )
          $iscc = $paths | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $iscc) { throw "ISCC.exe not found" }
          & "$iscc" SmartTimers.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SmartTimers-windows
          path: |
            dist/SmartTimers.exe
            release/SmartTimers_Setup_v*.exe
